-- 1. Сотрудники
CREATE TABLE employee (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    surname TEXT NOT NULL,
    name TEXT NOT NULL,
    patronymic TEXT,
    degree TEXT,
    title TEXT,
    phone TEXT,
    email TEXT,
    department_id INTEGER
);

-- 2. Факультет
CREATE TABLE faculty (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    dean_id INTEGER NOT NULL REFERENCES employee (id)
);

-- 3. Кафедра
CREATE TABLE department (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    faculty_id INTEGER NOT NULL REFERENCES faculty (id),
    head_id INTEGER NOT NULL REFERENCES employee (id),
    name TEXT NOT NULL,
    phones TEXT
);

-- 4. Ссылка сотрудника на кафедру (после создания department)
ALTER TABLE employee
    ADD CONSTRAINT fk_employee_department
    FOREIGN KEY (department_id) REFERENCES department (id);

-- 4a. Секции кафедр (предметно-методические секции: 0..n на кафедру, опционально — руководитель)
CREATE TABLE section (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id INTEGER NOT NULL REFERENCES department (id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    head_id INTEGER REFERENCES employee (id) ON DELETE SET NULL,
    phones TEXT
);

-- 4b. Сотрудник может быть привязан к секции (в рамках своей кафедры)
ALTER TABLE employee
    ADD COLUMN section_id INTEGER REFERENCES section (id) ON DELETE SET NULL;

-- 5. Специальность
CREATE TABLE specialty (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    qualification TEXT,
    duration INTEGER,
    form_of_study TEXT
);

-- 6. Дисциплина (кафедра преподаёт)
CREATE TABLE discipline (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id INTEGER NOT NULL REFERENCES department (id),
    name TEXT NOT NULL
);

-- 7. Учёт дисциплины по специальности в семестре
CREATE TABLE curriculum_item (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    discipline_id INTEGER NOT NULL REFERENCES discipline (id),
    specialty_id INTEGER NOT NULL REFERENCES specialty (id),
    semester INTEGER NOT NULL,
    lecture_hours INTEGER NOT NULL DEFAULT 0,
    lab_hours INTEGER NOT NULL DEFAULT 0,
    usr_hours INTEGER NOT NULL DEFAULT 0,
    practical_hours INTEGER NOT NULL DEFAULT 0,
    has_course_project BOOLEAN NOT NULL DEFAULT FALSE,
    is_credit BOOLEAN NOT NULL DEFAULT FALSE,
    is_exam BOOLEAN NOT NULL DEFAULT FALSE
);

-- Уникальность: одна дисциплина + специальность + семестр — одна запись
CREATE UNIQUE INDEX idx_curriculum_item_unique
    ON curriculum_item (discipline_id, specialty_id, semester);

-- Комментарии к таблицам (по diagrams.md)
COMMENT ON TABLE faculty IS 'Факультет; деканом является один из сотрудников';
COMMENT ON TABLE employee IS 'Сотрудники: ФИО, учёная степень, звание, контакты';
COMMENT ON TABLE specialty IS 'Специальность: код, название, квалификация, продолжительность, форма обучения';
COMMENT ON TABLE department IS 'Кафедра: название, телефоны, факультет, заведующий';
COMMENT ON TABLE discipline IS 'Дисциплина: название, кафедра';
COMMENT ON TABLE curriculum_item IS 'Учёт дисциплины по специальности в семестре: часы, курсовой проект, экзамен/зачёт';
COMMENT ON TABLE section IS 'Предметно-методическая секция кафедры: название, руководитель (опционально), контакты';
COMMENT ON COLUMN employee.section_id IS 'Секция в рамках кафедры (department_id); опционально';
