CREATE TABLE public.audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    actor_user_id UUID,
    actor_display_name TEXT,
    action TEXT NOT NULL CHECK (action IN ('INSERT', 'UPDATE', 'DELETE')),
    table_name TEXT NOT NULL,
    entity_id TEXT,
    old_row JSONB,
    new_row JSONB
);

COMMENT ON TABLE public.audit_log IS 'Аудит изменений: кто, когда и что изменил/удалил/создал';
COMMENT ON COLUMN public.audit_log.actor_user_id IS 'auth.uid() пользователя в момент операции';
COMMENT ON COLUMN public.audit_log.actor_display_name IS 'Отображаемое имя пользователя в момент операции (снимок из JWT claims)';
COMMENT ON COLUMN public.audit_log.entity_id IS 'Значение поля id изменяемой сущности';

CREATE INDEX idx_audit_log_occurred_at_desc ON public.audit_log (occurred_at DESC);
CREATE INDEX idx_audit_log_table_name ON public.audit_log (table_name);

REVOKE ALL ON public.audit_log FROM PUBLIC;
REVOKE SELECT ON public.audit_log FROM app_readonly;

CREATE OR REPLACE FUNCTION public.is_app_admin()
RETURNS BOOLEAN
LANGUAGE sql
STABLE
AS $$
    SELECT COALESCE(auth.jwt() -> 'app_metadata' ->> 'role', '') = 'admin';
$$;

CREATE OR REPLACE FUNCTION public.audit_log_row()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_entity_id TEXT;
    v_old_row JSONB;
    v_new_row JSONB;
    v_actor_display_name TEXT;
BEGIN
    IF TG_OP = 'INSERT' THEN
        v_entity_id := to_jsonb(NEW) ->> 'id';
        v_old_row := NULL;
        v_new_row := to_jsonb(NEW);
    ELSIF TG_OP = 'UPDATE' THEN
        v_entity_id := COALESCE(to_jsonb(NEW) ->> 'id', to_jsonb(OLD) ->> 'id');
        v_old_row := to_jsonb(OLD);
        v_new_row := to_jsonb(NEW);
    ELSIF TG_OP = 'DELETE' THEN
        v_entity_id := to_jsonb(OLD) ->> 'id';
        v_old_row := to_jsonb(OLD);
        v_new_row := NULL;
    ELSE
        RETURN COALESCE(NEW, OLD);
    END IF;

    v_actor_display_name := COALESCE(
        NULLIF(auth.jwt() -> 'user_metadata' ->> 'full_name', ''),
        NULLIF(auth.jwt() ->> 'email', ''),
        auth.uid()::text,
        '-'
    );

    INSERT INTO public.audit_log (
        occurred_at,
        actor_user_id,
        actor_display_name,
        action,
        table_name,
        entity_id,
        old_row,
        new_row)
    VALUES (now(), auth.uid(), v_actor_display_name, TG_OP, TG_TABLE_NAME, v_entity_id, v_old_row, v_new_row);

    RETURN COALESCE(NEW, OLD);
END;
$$;

ALTER TABLE public.audit_log ENABLE ROW LEVEL SECURITY;

CREATE POLICY "authenticated_select_audit_log_admin"
    ON public.audit_log
    FOR SELECT
    TO authenticated
    USING (public.is_app_admin());

DROP TRIGGER IF EXISTS trg_audit_employee ON public.employee;
CREATE TRIGGER trg_audit_employee
AFTER INSERT OR UPDATE OR DELETE ON public.employee
FOR EACH ROW EXECUTE FUNCTION public.audit_log_row();

DROP TRIGGER IF EXISTS trg_audit_faculty ON public.faculty;
CREATE TRIGGER trg_audit_faculty
AFTER INSERT OR UPDATE OR DELETE ON public.faculty
FOR EACH ROW EXECUTE FUNCTION public.audit_log_row();

DROP TRIGGER IF EXISTS trg_audit_department ON public.department;
CREATE TRIGGER trg_audit_department
AFTER INSERT OR UPDATE OR DELETE ON public.department
FOR EACH ROW EXECUTE FUNCTION public.audit_log_row();

DROP TRIGGER IF EXISTS trg_audit_section ON public.section;
CREATE TRIGGER trg_audit_section
AFTER INSERT OR UPDATE OR DELETE ON public.section
FOR EACH ROW EXECUTE FUNCTION public.audit_log_row();

DROP TRIGGER IF EXISTS trg_audit_specialty ON public.specialty;
CREATE TRIGGER trg_audit_specialty
AFTER INSERT OR UPDATE OR DELETE ON public.specialty
FOR EACH ROW EXECUTE FUNCTION public.audit_log_row();

DROP TRIGGER IF EXISTS trg_audit_discipline ON public.discipline;
CREATE TRIGGER trg_audit_discipline
AFTER INSERT OR UPDATE OR DELETE ON public.discipline
FOR EACH ROW EXECUTE FUNCTION public.audit_log_row();

DROP TRIGGER IF EXISTS trg_audit_curriculum_item ON public.curriculum_item;
CREATE TRIGGER trg_audit_curriculum_item
AFTER INSERT OR UPDATE OR DELETE ON public.curriculum_item
FOR EACH ROW EXECUTE FUNCTION public.audit_log_row();
